Discount coupons initial
termitnjak/bda.plone.discount pull request #1
Opened 2017-01-30 11:44 UTC by persho

This PR implements a basic coupon code functionality to bda.plone.discount. The coupon codes are managed through an existing item/cart discount settings page, where a new table is added for coupon management. In addition, a viewlet is added to enable users to input a coupon code, which is then stored in a cookie. The discount core reads the information form a cookie and finds an appropriate discount rule to be applied.

Only manual testing has been performed, no automatic tests yet.

2017-01-31 08:48 UTC, usatko requested changes
In templates we normally user different indent. Please unify the indentation , as it is other page templates in package.

2017-01-31 08:53 UTC, usatko approved these changes

2017-01-31 08:59 UTC, usatko requested changes
I do not know why is here a try/except. Also some comments about code readability.

2017-01-31 08:59 UTC, usatko commented on src/bda/plone/discount/calculator.py
> +            try:
Why is this in try/except? This was meat for debugging?

2017-01-31 08:59 UTC, usatko commented on src/bda/plone/discount/calculator.py
> +                lookups.append(self.coupon_lookup_factory(context, self.date, self.coupon))
To make code more readable, I would split this long append, as it is e.g. in line 134.

2017-01-31 08:59 UTC, usatko approved these changes

2017-01-31 09:00 UTC, usatko approved these changes

2017-01-31 09:04 UTC, usatko approved these changes
This changes look good.

2017-01-31 09:06 UTC, usatko approved these changes

2017-01-31 09:06 UTC, usatko approved these changes

2017-01-31 09:11 UTC, usatko requested changes
Curious about JavaScript callback.

2017-01-31 09:11 UTC, usatko commented on src/bda/plone/discount/browser/forms.py
> +#    for_callback = 'javascript:discount_form.autocomplete_group'
Why you comment out javascript callback? I think we do not need this here, or I am missing something?

2017-01-31 09:13 UTC, usatko approved these changes

2017-01-31 09:17 UTC, usatko approved these changes

2017-01-31 13:53 UTC, persho commented on src/bda/plone/discount/browser/forms.py
> +#    for_callback = 'javascript:discount_form.autocomplete_group'
So I copy pasted the class from GroupDiscountFormBase and removed the for_callback set to autocomplete groups. We only need a text field input and not autocomplete. Should I leave for_callback empty instead?

2017-01-31 14:14 UTC, persho commented on src/bda/plone/discount/calculator.py
> +            try:
Because I have implemented only coupons for CartItems and not also for Cart. I added try just for safety reasons. Should I remove it?

2017-02-02 08:16 UTC, jcerjak requested changes
Looks good in general, see comments.

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +from plone.app.layout.viewlets import common as base
Please use the `flake8` tool to fix unused imports, PEP8 issues etc.

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +        If we are on one of the checkout views return True, otherwise
The comment does not appear to be in sync with the code.

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +            self.request.response.redirect(url)
Seems weird that a viewlet does a redirect, why is this needed?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +            # Expire cookie in case if empty form was submitted, but not if site was reloaded
What do you mean by 'if site was reloaded'?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +
Add a short description what this viewlet does. Since we're basically just storing the coupon code in a cookie, we could do this also on the frontend. Though we also want to have some validation that the code is correct, where is this done?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/__init__.py
> +        # If no form has been submitted, check for coupon in the cookie
Looking at the `coupon_viewlet.pt`, seems that form will never be submitted here?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/coupon_viewlet.pt
> +	<div class="coupon_discount_viewlet" tal:define="couponcode view/existing_coupon_code">
use consistent spacing (2-spaces is used in other templates)

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/coupon_viewlet.pt
> +  			<!--span i18n:translate="">Coupon/Voucher:</span-->
can we remove this?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/coupon_viewlet.pt
> +    		<input type="text" name="couponcode" value="${couponcode}" placeholder="Coupon code">
spacing

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/configure.zcml
> +    manager="plone.app.layout.viewlets.interfaces.IPortalHeader"
Header seems like an awkward place for this viewlet.. How does this look on a default Plone site?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/browser/forms.py
> +
don't need spaces extra spaces here

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/calculator.py
> +        request = getRequest()
Maybe extract this section in a separate function? I we wanted to be super flexible, you could register a utility which would get the discount code (if someone wanted to get the coupon code from somewhere else).

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/settings.py
> +                msg = u'``coupon`` keyword must not be given if scope is user'
why not?

2017-02-02 08:16 UTC, jcerjak commented on src/bda/plone/discount/settings.py
> +                msg = u'``coupon`` keyword must not be given if scope is user'
Combining discounts is not possible?

2017-02-05 20:50 UTC, jcerjak commented on src/bda/plone/discount/browser/coupon_viewlet.pt
> +      <input type="text" name="couponcode"
let's use consistent spacing (2-spaces)

2017-02-05 21:01 UTC, jcerjak commented on src/bda/plone/discount/calculator.py
> +        # cookie
We have logic for getting the coupon code in two places (this is basically the same as "CouponViewlet.existing_coupon_code").

2017-02-13 16:02 UTC, merged